### ISSUE TITLE
[Update Request] to 1.20.1 & 1.20.2

### ISSUE THREAD

**Issue by xR4YM0ND** [RecraftorsMC/Dumpster#5]
Would be awesome if you could update this mod to the newest versions.

If you do so, pls close the issue so i get notified.

~ Would be an awesome help for our modpack running 1.20.1 soon and then 1.20.2

**Comment by NerjalNosk** [comment]
Hello,

Thank you for your interest in the mod.

Porting to newer versions of the mod is planned, but so far features implementation are the priority.
